Tweets Function
shinonome-inc/backend-final-assignment-nigel pull request #5
Opened 2023-10-28 12:23 UTC by keltX

## 受講生の確認事項

- [x] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/edit#gid=1308498917)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [x] Django Adminに，今まで作成したモデルを全て登録した
- [x] テスト要件のテストを全て実装した
- [x] CI が全て通った

## １次レビュアーの確認事項

- [x] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2023-11-20 03:58 UTC, TamanPG commented on tweets/models.py
> +    timestamp = models.DateTimeField(auto_now_add=True)
DateTimeFieldを使う場合は suffixが_atという命名にすることを推奨されているようです。
https://blog.pinkumohikan.com/entry/date-and-datetime-column-suffix-on-db

2023-11-20 04:02 UTC, TamanPG commented on tweets/forms.py
> +        fields = ["text"]
fieldsに文章のフィールドしかない場合はforms.pyに記載する必要なく、views.pyの方に記載すればOKです！

2023-11-21 04:31 UTC, TamanPG commented on tweets/forms.py
> +        tweet.author = self.instance.user  # Set the author to the current user
不要なコメントは消去しちゃってください。

2023-11-21 04:31 UTC, TamanPG commented on tweets/models.py
> +    timestamp = models.DateTimeField(auto_now_add=True)
DateTimeFieldを使う場合は suffixが_atという命名にすることを推奨されているようです。
https://blog.pinkumohikan.com/entry/date-and-datetime-column-suffix-on-db

2023-11-21 04:31 UTC, TamanPG commented on tweets/views.py
> +        return Tweet.objects.order_by("-timestamp")
N+1問題が起きてしまっています。select_related等で対応お願いします。

2023-11-21 04:36 UTC, keltX commented on tweets/models.py
> +    timestamp = models.DateTimeField(auto_now_add=True)
こちらはVariable名だけですね？承知しました。修正しました

2023-11-21 04:40 UTC, keltX commented on tweets/forms.py
> +        tweet.author = self.instance.user  # Set the author to the current user
forms.py 結局消したためこちら一応問題なし

2023-11-21 04:42 UTC, keltX commented on tweets/views.py
> +        return Tweet.objects.order_by("-timestamp")
修正しました

2023-11-23 13:13 UTC, TAK848 requested changes
数点ご確認お願いします！
また，PR出す段階でPRのDraftは解除してください！（自分でDraftで無くなった！という段階でレビュー依頼出してください！）

2023-11-23 13:13 UTC, TAK848 commented on accounts/views.py
> +    tweet = Tweet
https://ccbv.co.uk/projects/Django/4.2/django.views.generic.list/ListView/
ListViewでtweetというクラス変数はありませんが，どちらかで使う想定されてますか？

2023-11-23 13:13 UTC, TAK848 commented on tweets/__init__.py
https://qiita.com/msi/items/d91ea3900373ff8b09d7#__init__py-%E3%81%AE%E5%BD%B9%E5%89%B2
`__init__.py`は消さないでください！

2023-11-23 13:13 UTC, tak848 commented on templates/accounts/user_profile.html
> +    {% if is_author == user.username %}
`is_author`にusername(string)を入れていますが，`is_`となるとboolを普通想定します。
```suggestion
    {% if tweet.author == user %}
```
などで良いのでは無いでしょうか

2023-11-23 13:13 UTC, tak848 commented on tweets/tests.py
> +        self.user = User.objects.create_user(username="admin", password="testpassword")
ここはインスタンス変数である必要は無いと思います…！
また，userがadminとなっていますが，このテストの趣旨として，管理者などは関係ないので別の名前の方が読みやすいかと思います！

2023-11-23 13:24 UTC, keltX commented on tweets/__init__.py
自分で消さなかったのに、おそらく事前のmodels.pyのコメント通り tweetのattribute。 timestamp > created_atを変わる時。migrationsかmakemigrationsの時消されていましたかもしまでん

2023-11-23 13:30 UTC, keltX commented on tweets/tests.py
> +        self.user = User.objects.create_user(username="admin", password="testpassword")
ていうことは、self.user じゃなくてtest_userなどが大丈夫ででしょうか？一応修正しました

2023-11-23 14:05 UTC, keltX commented on templates/accounts/user_profile.html
> +    {% if is_author == user.username %}
そうなんですね！気づかなかったんです。ありがとうございます

2023-11-23 14:51 UTC, keltX commented on accounts/views.py
> +    tweet = Tweet
やっぱりLogicErrorが発生しまいました。tweetを消したしいくつのファイルも変わってしまいました一番西郷のコミットに

2023-11-29 03:29 UTC, TAK848 requested changes

2023-11-29 03:29 UTC, tak848 commented on accounts/views.py
> +        return context
これだと色々混ざってしまっていますね…。

ListViewって，指定したモデルをもとに，get_querysetで諸々取得して，それをobject_listという名前でcontextに渡してくれます。 https://docs.djangoproject.com/en/4.2/ref/class-based-views/generic-display/#listview
templates/accounts/user_profile.html では，これを使っていますね。

1. `context["tweets"] = self.get_queryset()`は使っていますか？
2. `model = User`としているのに，`super().get_queryset()`を呼んでおらず，指定の意味が無くなってしまっています。

ListViewについて調べてやってみてください。うまく実装すると，get_context_dataの中で，自身で
```
context["tweets"] = self.get_queryset()
```
のように代入する必要がなくなるはずです。ちなみにHomeViewはうまくできています。

あるいはですが，現状の実装を見るに，DetailViewにして，
```
class UserProfileView(ListView):
    model = User
    template_name = "accounts/user_profile.html"
    slug_field = "username"
```
とするのであれば，`object`に指定したユーザーのログイン情報が入り，contextでtweetsを追加するという実装も納得がいきます。調べてみてください。

2023-11-29 03:29 UTC, TAK848 commented on accounts/views.py
> +        return context
ちなみに`context_object_name`というクラス変数を使うと，object_listという名前をtweetsなどにも変更できます。

2023-11-29 03:29 UTC, TAK848 commented on templates/accounts/user_profile.html
> +    {% if tweet.author.username == user_profile %}
ここでフィルタする必要無いのでは…？既にフィルタしてるし

2023-11-29 03:31 UTC, TAK848 commented on tweets/tests.py
> +        self.user = User.objects.create_user(username="admin", password="testpassword")
インスタンス変数を使ってスコープが広がっているのが問題なので，test_userでもuserでも何でも良いです。

2023-11-29 03:31 UTC, TAK848 commented on tweets/__init__.py
変わらず消えているので復元してください！

2023-11-29 03:32 UTC, tak848 commented on tweets/__init__.py
migrationをいじって消えるファイルでは無いと思うのでなにかのオペミスかなとは思いますが復元しましょう！

2023-12-03 09:11 UTC, keltX commented on tweets/__init__.py
一番最新のコミットに修正したかまだ変わらないか教えてほしいです

2023-12-03 09:12 UTC, keltX commented on accounts/views.py
> +        return context
こちらも最新のコミットに修正したかまだ変わらないか教えてほしいです

2023-12-07 01:52 UTC, TAK848 commented on tweets/__init__.py
なおってますね！OKです！

2023-12-07 02:05 UTC, TAK848 requested changes

2023-12-07 02:05 UTC, TAK848 commented on accounts/views.py
> +        return context
tweets/views.py のDetailViewとListViewの使い方は適切なんですが，ここでListViewとしているのにこの機能を全く使えていない状態になっています。
contextに全部手動で与えるのであれば，TemplateViewで十分です！
https://ccbv.co.uk/projects/Django/4.2/django.views.generic.base/TemplateView/

DetailViewやListViewについてあらためて調べて，
1. TemplateViewを使う（現状の，get_context_dataを使ってUserと全てのTweetを渡すのでOK）
2. DetailView（modelをUserにして，指定した1つのUserを取得するのに使う，Tweet一覧**のみ**get_context_dataで追加で渡す）
3. ListView（modelをTweetにして，ユーザー絞り込みを行った複数のTweetを表示するのに使う，ProfileのUser**のみをget_context_dataで渡す）
のいずれかの方針でやってみてください。UserProfileという趣旨的には，3はあまり選択しないかも。
手っ取り早くやるなら1かな…？

2023-12-07 02:05 UTC, TAK848 commented on accounts/views.py
> +        context["tweets"] = Tweet.objects.filter(author=context["user_profile"])
この実装の場合，`context["user_profile"]`を使い回すよりはlocal変数化してあげた方がわかりやすいかなと思います！
```suggestion
        user = User.objects.get(username=self.kwargs["username"])
        context["user_profile"] = user
        context["tweets"] = Tweet.objects.filter(author=user)
```

2023-12-07 02:14 UTC, keltX commented on accounts/views.py
> +        return context
一応、１にしたんで、このあと２と３を勉強するつもりです。先ほどプッシュしましたのでご確認お願いします。

2023-12-09 05:13 UTC, TAK848 approved these changes
LGTM

2023-12-09 05:13 UTC, merged